
language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

addons:
  apt:
    packages:
      numpy-python
      numpy-matplotlib
      cython

script:
  - python setup.py install

notifications:
  email:
    - andreas.heger@gmail.com
