
language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

sudo: false

addons:
  apt:
    packages:
      - python-numpy
      - python-matplotlib
      - python-scipy
      - python-nose
      - cython
      - liblapack-dev
      - libblas-dev
      - libatlas-dev
      - gfortran

script:
  - python setup.py develop && nosetest -v test

notifications:
  email:
    - andreas.heger@gmail.com
