
language: python

python:
  - "2.7"
#  - "3.3"
#  - "3.4"

addons:
  apt:
    packages:
      - python-numpy
      - python-matplotlib
      - python-scipy
      - cython
      - liblapack-dev
      - libblas-dev
      - libatlas-dev
      - gfortran

script:
  - python setup.py install

notifications:
  email:
    - andreas.heger@gmail.com
