
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: false

addons:
  apt:
    packages:
      - python-numpy
      - python-matplotlib
      - python-scipy
      - python-nose
      - cython
      - liblapack-dev
      - libblas-dev
      - libatlas-dev
      - gfortran

script:
  - python setup.py develop && nosetests -v test/test_*.py

notifications:
  email:
    - andreas.heger@gmail.com
